FROM node:22-alpine AS builder
WORKDIR /app

ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_STORE_NAME
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_RAZORPAY_KEY_ID
ARG NEXT_PUBLIC_WHATSAPP_NUMBER
ARG NEXT_PUBLIC_WHATSAPP_DEFAULT_MESSAGE

ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-https://tanavidesigns.com}
ENV NEXT_PUBLIC_STORE_NAME=${NEXT_PUBLIC_STORE_NAME:-"Tanavi by Deepika"}
ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-https://wnbckffbhhmxxjbetzvs.supabase.co}
ENV NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:-sb_publishable_nc4EgAvRw9x3jQIYXQ1-Jw_BBfHGSC8}
ENV NEXT_PUBLIC_RAZORPAY_KEY_ID=${NEXT_PUBLIC_RAZORPAY_KEY_ID:-rzp_test_tanavi_key_id}
ENV NEXT_PUBLIC_WHATSAPP_NUMBER=${NEXT_PUBLIC_WHATSAPP_NUMBER:-919482245679}
ENV NEXT_PUBLIC_WHATSAPP_DEFAULT_MESSAGE=${NEXT_PUBLIC_WHATSAPP_DEFAULT_MESSAGE:-"Hello Tanavi, I would like to know more about your latest designer collection."}

COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app ./
RUN mkdir -p .wrangler/logs

EXPOSE 3000
CMD ["npm", "run", "start"]
